# The playbook.
# It will take a while to run all of this
# You can restrict how much you run using tags.

- name: Run fact gathering
  hosts: all

- name: Configure common roles
  hosts: all
  roles:
    - role: sown_common
      tags: sown_common
    - role: monitored
      tags: monitored
    - role: unattended_upgrades
      tags: unattended_upgrades
    - role: cron_mail_redirect
      tags: cron_mail_redirect
  tags: common

- name: Configure router roles
  hosts: device_roles_router
  roles:
    - role: pxe
      tags: pxe
    - role: dns_slave
      tags: dns_slave
    - role: gw
      tags: gw

- name: Configure backups
  hosts: tags_backup
  roles:
    - backed_up
  tags: backed_up

- name: Configure ssh gateways
  hosts: device_roles_ssh-gateway
  roles:
    - role: ssh_gateway
      tags: ssh_gateway

- name: Configure VM hosts
  hosts: device_roles_lxd-host
  roles:
    - role: vms
      tags: vms

- name: Configure containers-dev
  hosts: CONTAINERS-1
  roles:
    - role: docker
      tags: docker
    - role: docker_traefik
      tags: docker-traefik
    - role: docker_ferry
      tags: docker-ferry
    - role: docker_kmibot
      tags: docker-kmibot
    - role: docker_kmicms
      tags: docker-kmicms
    - role: docker_netbox
      tags: docker-netbox
