plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox.sown.org.uk
config_context: true
group_by:
  - device_roles
  - tags
query_filters:
  - status: active
  - role: virtual-machine-server
  - role: router
  - role: backup-server
  - role: server
  - role: ssh-gateway
