# Add the SOWN MOTD
- name: Install Common Packages for MOTD
  apt:
    name:
      - libpam-modules
      - base-files
    state: present
  become: true

- name: Install Ubuntu-specific Packages for MOTD
  apt:
    name:
      - ubuntu-release-upgrader-core
      - update-notifier-common
    state: present
  become: true
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- name: Generate figlet for /etc/motd
  delegate_to: localhost
  command: >
    figlet -f /usr/share/figlet/smslant.flf
    "{{ motd_org_name | default('SOWN') }}
    {{ inventory_hostname | lower }}"

  register: sown_common_figlet
  changed_when: false
  check_mode: false

- name: Deploy /etc/motd
  copy:
    content: "Welcome to\n{{ sown_common_figlet.stdout }}\n"
    dest: /etc/motd
    mode: "644"
  become: true

# Remove old files

- name: Remove deprecated MOTD files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/motd.tail
    - /etc/update-motd.d/99-footer
    - /etc/update-motd.d/99-header
    - /etc/update-motd.d/09-sown-machinename
  become: true

# Remove unwanted MOTD messages

- name: Disable ESM messages in motd
  ansible.builtin.file:
    path: /var/lib/update-notifier/hide-esm-in-motd
    mode: "0644"
    state: touch
    modification_time: preserve
    access_time: preserve
