- name: Checkout kmibot into /opt/kmibot
  git:
    repo: https://github.com/sown/kmibot.git
    dest: /opt/kmibot
    version: eae7f0179b036ca174155c7984a9c0c074b69c36
  notify: Restart KMIBot

- name: Install extra config
  template:
    src: files/config.toml
    dest: /opt/kmibot/config.toml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: Restart KMIBot
